kind: pipeline
name: default
steps:
- name: docker  
  image: plugins/docker:17.05
  settings:
    username:
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASS
    repo: abhisheksanga/cachingservice
    tags:
      - latest
      - '1.0.1'
      - '1.0'

